"""add length prop to audio

Revision ID: 935221c83ab7
Revises: 
Create Date: 2023-11-23 22:35:32.093430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '935221c83ab7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('_length', sa.Float(), nullable=False))
        batch_op.drop_column('_label')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_label', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('_length')
        batch_op.drop_column('label')

    # ### end Alembic commands ###
