DROP TABLE IF EXISTS user;

CREATE TABLE user (
  id       INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);


DROP TABLE IF EXISTS audio;

CREATE TABLE audio (
  id                INTEGER PRIMARY KEY AUTOINCREMENT,
  title             TEXT NOT NULL,
  description       TEXT NOT NULL,
  date_created      TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_modified      TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(user) REFERENCES user(id) NOT NULL
);